name: Monitor de Email Policia

on:
  schedule:
    # Minuto 0
    # Horas: 10h às 23h UTC (equivale a 07h às 20h no horário local)
    # Dias: 1 (Segunda) até 6 (Sábado)
    - cron: '0 10-23 * * 1-6'
  workflow_dispatch: # Permite rodar manualmente clicando num botão se quiser testar

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar código
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Instalar bibliotecas
      run: |
        pip install requests PyPDF2

    - name: Rodar Script
      env:
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python monitor_bis.py
